on:
  push:
  schedule:
    - cron: '0 0 * * *'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: '3.x'
      - id: cached-poetry
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: poetry-0
      - if: steps.cached-poetry.outputs.cache-hit != 'true'
        uses: snok/install-poetry@v1
      - id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version
            }}-${{ hashFiles('poetry.lock') }}
      - if: steps.cached-poetry_dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction
      - run: poetry run python update.py ${{ secrets.GITHUB_TOKEN }}
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actor
          message: 'Updated readme'
